-- Migration: alias, age range, and corroborations
-- Run this against your live Supabase project via the SQL editor.

-- Add optional alias and age_range columns to reports
alter table public.reports add column if not exists alias text;
alter table public.reports add column if not exists age_range text;

-- Corroborations table: one per (report, submitter) enforced by unique constraint
create table if not exists public.report_corroborations (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  submitter_uuid text not null,
  created_at timestamptz not null default now(),
  unique(report_id, submitter_uuid)
);

alter table public.report_corroborations enable row level security;

create policy if not exists "Public can insert corroborations"
on public.report_corroborations
for insert
to anon, authenticated
with check (true);

create policy if not exists "Public can read corroborations"
on public.report_corroborations
for select
using (true);
